#pragma once

// TAKEN FROM IMGUI GLFW IMPL

// BUTTONS
#define MPE_MOUSE_BUTTON_1 0
#define MPE_MOUSE_BUTTON_2 1
#define MPE_MOUSE_BUTTON_3 2
#define MPE_MOUSE_BUTTON_4 3
#define MPE_MOUSE_BUTTON_5 4
#define MPE_MOUSE_BUTTON_6 5
#define MPE_MOUSE_BUTTON_7 6
#define MPE_MOUSE_BUTTON_8 7
#define MPE_MOUSE_BUTTON_LAST MPE_MOUSE_BUTTON_8
#define MPE_MOUSE_BUTTON_LEFT MPE_MOUSE_BUTTON_1
#define MPE_MOUSE_BUTTON_RIGHT MPE_MOUSE_BUTTON_2
#define MPE_MOUSE_BUTTON_MIDDLE MPE_MOUSE_BUTTON_3