if(WIN32)
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Dependencies/WIN32/dependencies_win32.cmake")
elseif(COMPILATION_PLATFORM STREQUAL "UNIX")
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Dependencies/UNIX/dependencies_unix.cmake")
elseif(COMPILATION_PLATFORM STREQUAL "OSX")
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Dependencies/OSX/dependencies_osx.cmake")
elseif(COMPILATION_PLATFORM STREQUAL "RPI4")
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Dependencies/RPI4/dependencies_rpi4.cmake")
else()
    message(FATAL_ERROR "${COMPILATION_PLATFORM} NOT SUPPORTED.")
endif()