if(WIN32)
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Source/WIN32/source_win32.cmake")
elseif(COMPILATION_PLATFORM STREQUAL "UNIX")
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Source/UNIX/source_unix.cmake")
elseif(COMPILATION_PLATFORM STREQUAL "OSX")
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Source/OSX/source_osx.cmake")
elseif(COMPILATION_PLATFORM STREQUAL "RPI4")
    include("${PROJECT_SOURCE_DIR}/CMake/Platform/Source/RPI4/source_rpi4.cmake")
else()
    message(FATAL_ERROR "${COMPILATION_PLATFORM} NOT SUPPORTED.")
endif()